# Generated by Django 4.2 on 2024-12-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestApp', '0002_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='exit', upload_to='team_images/'),
            preserve_default=False,
        ),
    ]
