# Generated by Django 4.2 on 2024-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestApp', '0003_remove_photo_url_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='team_images/'),
        ),
    ]
