# Generated by Django 4.2 on 2024-12-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestApp', '0005_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='opponent',
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.CharField(default='Default Away Team', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(default='Default Home Team', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default='Default Venue', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='upcoming_matches',
            field=models.ManyToManyField(related_name='upcoming_matches', to='QuestApp.match'),
        ),
    ]
