# Generated by Django 4.2 on 2024-12-04 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuestApp', '0006_remove_match_opponent_match_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_lineup',
            field=models.ManyToManyField(related_name='away_team_lineup', to='QuestApp.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_lineup',
            field=models.ManyToManyField(related_name='home_team_lineup', to='QuestApp.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_key_player',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestApp.match')),
            ],
        ),
    ]
